async function createChainModule(moduleArg={}){var moduleRtn;var d=moduleArg,n=!!globalThis.WorkerGlobalScope,aa=import.meta.url,p="",q,r;if(globalThis.window||n){try{p=(new URL(".",aa)).href}catch{}n&&(r=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});q=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var v=console.log.bind(console),w=console.error.bind(console),x,y=!1,z,A,B=!1;
function C(){var a=D.buffer;E=new Int8Array(a);F=new Int16Array(a);d.HEAPU8=G=new Uint8Array(a);new Uint16Array(a);H=new Int32Array(a);I=new Uint32Array(a);J=new Float32Array(a);K=new Float64Array(a);L=new BigInt64Array(a);new BigUint64Array(a)}function M(a){d.onAbort?.(a);a=`Aborted(${a})`;w(a);y=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");A?.(a);throw a;}var N;
async function ba(a){if(!x)try{var b=await q(a);return new Uint8Array(b)}catch{}if(a==N&&x)a=new Uint8Array(x);else if(r)a=r(a);else throw"both async and sync fetching of the wasm failed";return a}async function ca(a,b){try{var c=await ba(a);return await WebAssembly.instantiate(c,b)}catch(e){w(`failed to asynchronously prepare wasm: ${e}`),M(e)}}
async function da(a){var b=N;if(!x)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(e){w(`wasm streaming compile failed: ${e}`),w("falling back to ArrayBuffer instantiation")}return ca(b,a)}var F,H,L,E,J,K,I,G,O=a=>{for(;a.length>0;)a.shift()(d)},P=[],Q=[],ea=()=>{var a=d.preRun.shift();Q.push(a)};class fa{constructor(a){this.u=a-24}init(a,b){I[this.u+16>>2]=0;I[this.u+4>>2]=a;I[this.u+8>>2]=b}}
var ha=0,ia=[null,[],[]],R=globalThis.TextDecoder&&new TextDecoder,S=(a,b=0,c,e)=>{var f=b;c=f+c;if(e)e=c;else{for(;a[f]&&!(f>=c);)++f;e=f}if(e-b>16&&a.buffer&&R)return R.decode(a.subarray(b,e));for(f="";b<e;)if(c=a[b++],c&128){var h=a[b++]&63;if((c&224)==192)f+=String.fromCharCode((c&31)<<6|h);else{var g=a[b++]&63;c=(c&240)==224?(c&15)<<12|h<<6|g:(c&7)<<18|h<<12|g<<6|a[b++]&63;c<65536?f+=String.fromCharCode(c):(c-=65536,f+=String.fromCharCode(55296|c>>10,56320|c&1023))}}else f+=String.fromCharCode(c);
return f},T=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);e<=127?b++:e<=2047?b+=2:e>=55296&&e<=57343?(b+=4,++c):b+=3}return b},U=(a,b,c)=>{var e=G;if(!(c>0))return 0;var f=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(g<=127){if(b>=c)break;e[b++]=g}else if(g<=2047){if(b+1>=c)break;e[b++]=192|g>>6;e[b++]=128|g&63}else if(g<=65535){if(b+2>=c)break;e[b++]=224|g>>12;e[b++]=128|g>>6&63;e[b++]=128|g&63}else{if(b+3>=c)break;e[b++]=240|g>>18;e[b++]=128|g>>12&63;e[b++]=128|g>>
6&63;e[b++]=128|g&63;h++}}e[b]=0;return b-f},Y=(a,b,c,e)=>{var f={string:k=>{var l=0;if(k!==null&&k!==void 0&&k!==0){l=T(k)+1;var t=V(l);U(k,t,l);l=t}return l},array:k=>{var l=V(k.length);E.set(k,l);return l}};a=d["_"+a];var h=[],g=0;if(e)for(var m=0;m<e.length;m++){var u=f[c[m]];u?(g===0&&(g=W()),h[m]=u(e[m])):h[m]=e[m]}c=a(...h);return c=function(k){g!==0&&X(g);return b==="string"?k?S(G,k):"":b==="boolean"?!!k:k}(c)};d.print&&(v=d.print);d.printErr&&(w=d.printErr);d.wasmBinary&&(x=d.wasmBinary);
if(d.preInit)for(typeof d.preInit=="function"&&(d.preInit=[d.preInit]);d.preInit.length>0;)d.preInit.shift()();d.ccall=Y;d.cwrap=(a,b,c,e)=>{var f=!c||c.every(h=>h==="number"||h==="boolean");return b!=="string"&&f&&!e?d["_"+a]:(...h)=>Y(a,b,c,h,e)};
d.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":E[a]=b;break;case "i8":E[a]=b;break;case "i16":F[a>>1]=b;break;case "i32":H[a>>2]=b;break;case "i64":L[a>>3]=BigInt(b);break;case "float":J[a>>2]=b;break;case "double":K[a>>3]=b;break;case "*":I[a>>2]=b;break;default:M(`invalid type for setValue: ${c}`)}};
d.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return E[a];case "i8":return E[a];case "i16":return F[a>>1];case "i32":return H[a>>2];case "i64":return L[a>>3];case "float":return J[a>>2];case "double":return K[a>>3];case "*":return I[a>>2];default:M(`invalid type for getValue: ${b}`)}};d.UTF8ToString=(a,b,c)=>a?S(G,a,b,c):"";d.stringToUTF8=(a,b,c)=>U(a,b,c);d.lengthBytesUTF8=T;
var X,V,W,D,ja={b:(a,b,c)=>{(new fa(a)).init(b,c);ha++;M()},d:()=>M(""),c:a=>{var b=G.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,Math.ceil(Math.max(a,e)/65536)*65536)-D.buffer.byteLength+65535)/65536|0;try{D.grow(e);C();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},a:(a,b,c,e)=>{for(var f=0,h=0;h<c;h++){var g=I[b>>2],m=I[b+4>>2];b+=8;for(var u=0;u<m;u++){var k=a,l=G[g+u],t=ia[k];l===0||l===10?((k===
1?v:w)(S(t)),t.length=0):t.push(l)}f+=m}I[e>>2]=f;return 0}},Z;
Z=await (async function(){function a(c){c=Z=c.exports;d._mc_web_chain_transfer_sign_message=c.g;d._malloc=c.h;d._mc_web_chain_username_sign_message=c.i;d._mc_web_chain_to_checksum_hex=c.j;d._mc_web_chain_parse_address=c.k;d._mc_web_chain_sha256_hex=c.l;d._mc_web_chain_validate_hex_hash=c.m;d._free=c.n;X=c.o;V=c.p;W=c.q;D=c.e;C();return Z}var b={a:ja};if(d.instantiateWasm)return new Promise(c=>{d.instantiateWasm(b,(e,f)=>{c(a(e,f))})});N??=d.locateFile?d.locateFile?d.locateFile("chain.wasm",
p):p+"chain.wasm":(new URL("chain.wasm",import.meta.url)).href;return function(c){return a(c.instance)}(await da(b))}());
(function(){function a(){d.calledRun=!0;if(!y){B=!0;Z.f();z?.(d);d.onRuntimeInitialized?.();if(d.postRun)for(typeof d.postRun=="function"&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();P.push(b)}O(P)}}if(d.preRun)for(typeof d.preRun=="function"&&(d.preRun=[d.preRun]);d.preRun.length;)ea();O(Q);d.setStatus?(d.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>d.setStatus(""),1);a()},1)):a()})();B?moduleRtn=d:moduleRtn=new Promise((a,b)=>{z=a;A=b});
;return moduleRtn}export default createChainModule;
